version: '3'

services:
  docker-mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
    ports:
      - 3306:3306
  stock-handling-api:
    build: .
    depends_on:
      - docker-mysql
    ports:
      - 8432:8432
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=changeit
      - DATABASE_NAME=stockdb
      - DATABASE_PORT=3306