server:
  port: 8432

spring:
    datasource:
        url: jdbc:mysql://192.168.2.140:3306/stockdb?createDatabaseIfNotExist=true
        username: root
        password: 362578

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
logging:
#    level: trace
#    level.org.hibernate.SQL: trace
    level.org.hibernate.type.descriptor.sql: trace
    level.org.springframework.web: trace
